# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: my-new-service

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless
# The `functions` block defines what code to deploy
functions:
  helloworld:
    handler: handler.helloworld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node12-x:21
    environmentVariables:
      # Optional for trace_id log injection
      DD_LOGS_INJECTION: true
    plugins:
      - serverless-plugin-datadog
